### ISSUE TITLE
License and renaming

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-sm-annotations-conversion#1]
@CPBridge can you please add a permissive license to the repo?

Also I suggest we rename this repo to be more generic, how about idc-sm-annotations-conversion?

**Comment by CPBridge** [comment]
Good points @fedorov 

I just added a license (MIT).

Unfortunately I don't appear to have permissions to rename. As owner of the ImagingDataCommons organization, you might have to do that I'm afraid. But I agree that we should change it and that `idc-sm-annotations-conversion` would be a more suitable name.

**Comment by fedorov** [comment]
Renamed - thank you!
